version: '3.8'

services:
  postgres-db:
    build:
      context: .
      dockerfile: docker/postgres-prod/Dockerfile
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_PROD_NAME}
      POSTGRES_USER: ${DB_PROD_USER}
      POSTGRES_PASSWORD: ${DB_PROD_PASSWORD}
    ports:
      - "${DB_PROD_PORT}:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/proddata
      - ./pgdata:/var/lib/postgresql/proddata
    networks:
      - db-network
    restart: unless-stopped


  postgres-db-test:
    build:
      context: .
      dockerfile: docker/postgres-test/Dockerfile
    container_name: postgres-db-test
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
    ports:
      - "${DB_TEST_PORT}:5433"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/testdata
      - ./pgdata-test:/var/lib/postgresql/testdata
    networks:
      - db-network
    restart: unless-stopped

volumes:
  postgres_prod_data:
    driver: local
  postgres_test_data:
    driver: local

networks:
  db-network:
    driver: bridge