spring.cache.type: none
spring:

  config:
    activate:
      on-profile: test
    import: optional:file:.env[.properties]

  init:
    mode: always
  datasource:
    url: ${DB_TEST_URL}
    username: ${DB_TEST_USER}
    password: ${DB_TEST_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true